-- Add Target Start and Actual Start columns for IFR, IFA, IFB
ALTER TABLE prabumulih_monitoring_data 
ADD COLUMN target_start_ifr TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN target_start_ifa TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN target_start_ifb TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN actual_start_ifr TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN actual_start_ifa TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN actual_start_ifb TIMESTAMP WITH TIME ZONE DEFAULT NULL;